---
- include: install.yml
  become: true
  when: ansible_distribution == "Ubuntu"
  tags:
   - install_nginx

- include: node_exporter.yml
  become: true
  when: ansible_distribution == "Ubuntu"
  tags:
   - install_node_exporter

- include: configuration.yml
  become: true
  when: ansible_distribution == "Ubuntu"
  tags:
   - install_nginx

- include: wordpress_install.yml
  become: true
  when: ansible_distribution == "Ubuntu"
  tags:
   - install_wordpress

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: true

- name: debug ansible_hostname
  debug: var={{ansible_hostname}}