---
- name: Create document root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: '{{ nginx_user }}'
    group: '{{ nginx_group }}'
    mode: '0755'

- name: Dowland and unpack latest wordpress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/{{ http_host }}"
    remote_src: yes
    creates: "/var/www/{{ http_host }}/wordpress"
  
- name: Set
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    recurse: yes
    owner: '{{ nginx_user }}'
    group: '{{ nginx_group }}'

- name: Update wp_conf file
  template: 
     src: wp-config.php.j2
     dest: /var/www/{{ http_host }}/wordpress/wp-config.php
     owner: '{{ nginx_user }}'
     group: '{{ nginx_group }}'
     mode: 0644
  become: true

- name: symlink default catchall
  file:
    src: "/etc/nginx/sites-available/default"
    dest: "/etc/nginx/sites-enabled/default"
    state: link

- name: restart 'php7.4-fpm'
  systemd:
    name: php7.4-fpm
    state: restarted
    enabled: yes
  become: true

- name: enable nginx daemon
  systemd:
    name: nginx
    state: started
    enabled: yes
  become_user: 'www-data'
