---
- name: delete config nginx
  shell: rm /etc/nginx/sites-available/default
  become: true

- name: Update nginx reverce proxy 
  template: 
    src: default
    dest: /etc/nginx/sites-available/default
    owner: '{{ nginx_user }}'
    group: '{{ nginx_group }}'
    mode: 0644
  become: true

- name: symlink default catchall
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: 
    - start nginx