---
- include_tasks: install.yml
- include_tasks: node_exporter.yml
- include_tasks: configuration.yml
- include_tasks: certbot.yml

- name: resrat nginx
  service:
    name: nginx
    state: restarted
  become: true