---
- include: install.yml
  become: true
  when: ansible_distribution == "Ubuntu"
  tags:
   - install_nginx

- include: configuration.yml
  become: true
  when: ansible_distribution == "Ubuntu"
  tags:
   - install_nginx

- name: resrat nginx
  service:
    name: nginx
    state: restarted
  become: true