- name: Copy GitLab configuration file.
  template:
    src: gitlab.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
    backup: yes

- name: Reconfigure GitLab (first run).
  command: >
    gitlab-ctl reconfigure
  failed_when: false