---
- name: Check source list for GitLab exists
  register: check_source_list
  stat:
    path: "/etc/apt/sources.list.d/runner_{{ gitlab_runner_package_name }}.list"

- name: Download script for setup GitLab's official repository
  register: script_for_setup_gitlab_repo
  get_url:
    url: "{{ gitlab_runner_package_name }}"
    dest: "/tmp/runnet_gitlab.script.deb.sh"
    mode: "0744"

- name: run repository installation script
  command: "/tmp/runnet_gitlab.script.deb.sh"
  register: command_resultat
  become: true

- name: install gitlab-runner 
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - gitlab-runner

- name: register runner 
  block:
    - name: get registration status 
      command:
        cmd: gitlab-runner list
      register: gitlab_runner_get_registration_status
      changed_when: no 

- name: Register GitLab runner 
  become: true 
  command: gitlab-runner register -n --url http://gitlab --registration-token {{ token }} --executor shell --description "Shell Runner" --tag-list deployment

- name: start and enable gitlab-runner
  service:
    name: gitlab-runner
    state: started
    enabled: yes