---
- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: true

- name: reload nginx
  service:
    name: nginx
    state: reloaded
  become: true

- name: start nginx
  service:
    name: nginx
    state: started
  become: true