---
# install ansible-galaxy collection install community.mysql
- include_tasks: install.yml # install mysql server and packer
- include_tasks: databases.yml #create mysql databases
- include_tasks: users.yml # creating root-user databases

- include: node_exporter.yml
  become: true
  when: ansible_distribution == "Ubuntu"
  tags:
   - install_node_exporter

- include_tasks: replication.yml
