---
 - name: installing tools
   apt: >
    name={{ item }}
    state=present
    update_cache=yes
   loop: "{{ php_modules }}"
   tags: [ system ]

 - name: Delete /var/www/*
   shell: "rm -rf /var/www/* /etc/nginx/sites-available/*"
   become: true

 - name: Create document root
   file:
     path: "/var/www/{{ http_host }}"
     state: directory
     owner: "www-data"
     group: "www-data"
     mode: '0755'
     
 - name: Dowland and unpack latest wordpress
   unarchive:
     src: https://wordpress.org/latest.tar.gz
     dest: "/var/www/{{ http_host }}"
     remote_src: yes
     creates: "/var/www/{{ http_host }}/wordpress"

 - name: Set
   file:
     path: "/var/www/{{ http_host }}"
     state: directory
     recurse: yes
     owner: "www-data"
     group: "www-data"

 - name: Set permission for directories
   shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type d -exec chmod 750 {} \\;"

 - name: Set permission for files
   shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type f -exec chmod 640 {} \\;"

 - name: Update nginx confs for wordpress
   template: "src=../templates/default dest=/etc/nginx/sites-available/default owner=www-data group=www-data mode=0644"
   become: true

 - name: Update nginx confs for wordpress
   template: "src=../templates/www.conf dest=/etc/php/7.4/fpm/pool.d/www.conf"
   become: true

 - name: symlink default catchall
   file:
     src: "/etc/nginx/sites-available/default"
     dest: "/etc/nginx/sites-enabled/default"
     state: link

 - name: restart 'php7.4-fpm'
   systemd:
     name: php7.4-fpm
     state: restarted
     enabled: yes

 - name: enable nginx daemon
   systemd:
     name: nginx
     state: started
     enabled: yes