---
# - name: create alertmanager system group
#   group:
#     name: "{{ groupId }}"
#     system: true
#     state: present 

# - name: create alertmanager system user
#   user:
#     name: "{{ userId }}"
#     system: true
#     shell: "/usr/sbin/nologin"
#     group: "{{ groupId }}"
#     createhome: false

# - name: creating alertmanager config directories
#   file:
#     path: "{{ item }}"
#     state: directory
#     owner: "{{ userId }}"
#     group: "{{ groupId }}"
#     mode: 0770
#   with_items: 
#     - "/etc/alertmanager"

# - name: Dowlanding alertmanager binary files
#   unarchive:
#     src: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
#     dest: "/tmp"
#     remote_src: yes

- name: Copy alertmanager cpmpressed file
  copy:
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/"
    mode: 0755
    owner: "{{ userId }}"
    group: "{{ groupId }}"
    remote_src: yes
  with_items:
    - alertmanager

- name: creating alertmanager SystemD unit 
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
    owner: "{{ userId }}"
    group: "{{ groupId }}"
    mode: 0644

- name: copying alertmanager.yml file
  template:
    src: alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    owner: "{{ userId }}"
    group: "{{ groupId }}"
    mode: 0755

- name: start alertmanager
  service:
    name: alertmanager
    state: started