---
prometheus_version: 2.13.1
prometheus_service_reload: true
prometheus_release_name: "prometheus-{{ prometheus_version }}.linux-amd64"
prometheus_root_dir: /etc/prometheus/
prometheus_tsdb: /data/prometheus 
prometheus_user: "prometheus"
prometheus_group: "prometheus"
exec_command: "/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/data/prometheus --storage.tsdb.retention=2d"

#Графана
grafana_admin_password: wordpress

    # - grafana_data:/var/lib/grafana
    #   - ./grafana/provisioning:/etc/grafana/provisioning

#alter manager
prometheus_alertmanager_config_file: /etc/alertmanager/alertmanager.yml
prometheus_alertmanager_storage_path: /etc/systemd/system/
exec_command_aler: "alertmanager --config.file=/etc/alertmanager/alertmanager.yml --log.level=debug"
serviceNamealter: "Alertmanager Service"
alertmanager_version: '0.24.0'
userId: "alertmanager"
groupId: "alertmanager"
versian_go: '1.19'
