---
node_exporter_version: 1.1.2
node_exporter_bin_path: /usr/local/bin/node_exporter
node_exporter_host: "localhost"
node_exporter_port: 9100
node_exporter_options: ''
node_user: "node_exporter"
node_group: "node_exporter"


prometheus_version: 2.13.1
prometheus_service_reload: true
prometheus_release_name: "prometheus-{{ prometheus_version }}.linux-amd64"
prometheus_root_dir: /etc/prometheus/
prometheus_tsdb: /data/prometheus 
prometheus_user: "prometheus"
prometheus_group: "prometheus"
exec_command: "/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/data/prometheus --storage.tsdb.retention=2d"

#Графана
grafana_admin_password: wordpress

    # - grafana_data:/var/lib/grafana
    #   - ./grafana/provisioning:/etc/grafana/provisioning

#alter manager
alertbinary: ['git', 'go', 'make']
exec_command_alter: "alertmanager --config.file=/etc/alertmanager/alertmanager.yml"
serviceNamealter: "alertmanager"
alertmanager_version: '0.24.0'
userId: "alertmanager"
groupId: "alertmanager"
versian_go: '1.19'
